export const sampleClients = [
  {
    id: 'c001',
    mandantennummer: '10042',
    name: 'Müller Maschinenbau GmbH',
    rechtsform: 'GmbH',
    gewinnermittlung: 'Bilanz',
    veranlagungsjahr: 2024,
    archiviert: false,
    rueckfragen: [
      { id: 'rq1', text: 'Belege für Fahrzeugkosten Q3 2024 fehlen', beantwortet: true, beantwortetAm: '2026-02-15' },
      { id: 'rq2', text: 'Kontoauszug Dezember 2024 ausstehend', beantwortet: true, beantwortetAm: '2026-02-20' },
    ],
    inBearbeitung: true,
    rueckfragenGesendetDatum: '2026-02-05',
    abschlussFertig: true,
    abschlussFertigDatum: '2026-02-20',
    steGesendetDatum: '2026-02-22',
    unterschriftDatum: '2026-02-28',
    faGeplantDatum: '2026-03-10',
    faUebermittelt: false,
    faUebermitteltDatum: null,
    erinnerungen: [
      { id: 'e1', datum: '2026-03-10', text: 'FA-Übermittlung termingerecht durchführen' },
    ],
    notizen: 'Mandant bevorzugt Kontakt per E-Mail. Jahresabschluss 2023 war problemlos.\nAnsprechpartner: Hr. Müller (GF), Tel. intern.',
    archivSummary: '',
    archivDatum: null,
    berechnungen: { kfz: [], arbeitszimmer: [], reisekosten: [] },
  },
  {
    id: 'c002',
    mandantennummer: '10078',
    name: 'Schreiber & Partner KG',
    rechtsform: 'KG',
    gewinnermittlung: 'EÜR',
    veranlagungsjahr: 2024,
    archiviert: false,
    rueckfragen: [
      { id: 'rq1', text: 'Betriebsausgaben Homeoffice 2024 belegen', beantwortet: true, beantwortetAm: '2026-02-10' },
      { id: 'rq2', text: 'Gesellschaftervertrag – aktuelle Fassung anfordern', beantwortet: false, beantwortetAm: null },
    ],
    inBearbeitung: true,
    rueckfragenGesendetDatum: '2026-02-03',
    abschlussFertig: false,
    abschlussFertigDatum: null,
    steGesendetDatum: '2026-02-25',
    unterschriftDatum: null,
    faGeplantDatum: '2026-03-20',
    faUebermittelt: false,
    faUebermitteltDatum: null,
    erinnerungen: [
      { id: 'e1', datum: '2026-03-05', text: 'Unterschrift / VE anmahnen – Fr. Partner kontaktieren' },
    ],
    notizen: 'Zwei Gesellschafter: Hr. Schreiber (60 %) und Fr. Partner (40 %). Rückfragen immer an Hr. Schreiber.',
    archivSummary: '',
    archivDatum: null,
    berechnungen: { kfz: [], arbeitszimmer: [], reisekosten: [] },
  },
  {
    id: 'c003',
    mandantennummer: '10113',
    name: 'Dr. Anna Bergmann',
    rechtsform: 'Freiberufler',
    gewinnermittlung: 'EÜR',
    veranlagungsjahr: 2024,
    archiviert: false,
    rueckfragen: [
      { id: 'rq1', text: 'Fortbildungskosten 2024 mit Belegen nachreichen', beantwortet: false, beantwortetAm: null },
      { id: 'rq2', text: 'Kranken- und Pflegeversicherungsbeiträge mitteilen', beantwortet: false, beantwortetAm: null },
      { id: 'rq3', text: 'Arbeitszimmer: Quadratmeteranteil und Mietspiegel angeben', beantwortet: false, beantwortetAm: null },
    ],
    inBearbeitung: true,
    rueckfragenGesendetDatum: '2026-01-30',
    abschlussFertig: false,
    abschlussFertigDatum: null,
    steGesendetDatum: null,
    unterschriftDatum: null,
    faGeplantDatum: null,
    faUebermittelt: false,
    faUebermitteltDatum: null,
    erinnerungen: [
      { id: 'e1', datum: '2026-02-28', text: 'Rückfragen ausstehend – Follow-up per E-Mail' },
    ],
    notizen: '',
    archivSummary: '',
    archivDatum: null,
    berechnungen: { kfz: [], arbeitszimmer: [], reisekosten: [] },
  },
  {
    id: 'c004',
    mandantennummer: '10055',
    name: 'TechStart GmbH',
    rechtsform: 'GmbH',
    gewinnermittlung: 'Bilanz',
    veranlagungsjahr: 2024,
    archiviert: false,
    rueckfragen: [],
    inBearbeitung: true,
    rueckfragenGesendetDatum: null,
    abschlussFertig: true,
    abschlussFertigDatum: '2026-01-15',
    steGesendetDatum: '2026-01-20',
    unterschriftDatum: '2026-02-05',
    faGeplantDatum: '2026-02-28',
    faUebermittelt: false,
    faUebermitteltDatum: null,
    erinnerungen: [],
    notizen: 'Neuer Mandant seit 2024. GF: Hr. Keller. Erstes Jahr mit Bilanzpflicht.',
    archivSummary: '',
    archivDatum: null,
    berechnungen: { kfz: [], arbeitszimmer: [], reisekosten: [] },
  },
  {
    id: 'c005',
    mandantennummer: '10031',
    name: 'Fischer Handelsunternehmen',
    rechtsform: 'Einzelunternehmen',
    gewinnermittlung: 'EÜR',
    veranlagungsjahr: 2024,
    archiviert: false,
    rueckfragen: [
      { id: 'rq1', text: 'Umsatzsteuervoranmeldung Q4 geprüft?', beantwortet: true, beantwortetAm: '2026-01-20' },
    ],
    inBearbeitung: true,
    rueckfragenGesendetDatum: null,
    abschlussFertig: true,
    abschlussFertigDatum: '2026-01-25',
    steGesendetDatum: '2026-02-01',
    unterschriftDatum: '2026-02-10',
    faGeplantDatum: '2026-02-15',
    faUebermittelt: true,
    faUebermitteltDatum: '2026-02-14',
    erinnerungen: [],
    notizen: 'Jahresabschluss 2024 vollständig abgeschlossen. Mandant sehr zuverlässig und pünktlich.\nFür 2025 bitte Umsatzgrenzen prüfen (Bilanzierungspflicht?).',
    archivSummary: '',
    archivDatum: null,
    berechnungen: { kfz: [], arbeitszimmer: [], reisekosten: [] },
  },
]
